### ISSUE TITLE
TypeError: Not a Buffer

### ISSUE THREAD

**Issue by danielmahon** [transloadit/node-sdk#2]
Every now and then I seem to get stuck with this error? Not sure where the problem lies:

```
16:12:23 web.1  | TypeError: Not a buffer
16:12:23 web.1  |   at new Hmac (crypto.js:257:17)
16:12:23 web.1  |   at Object.Hmac (crypto.js:255:12)
16:12:23 web.1  |   at TransloaditClient.calcSignature (~/Projects/keystone/node_modules/transloadit/lib/TransloaditClient.js:228:21)
16:12:23 web.1  |   at TransloaditClient._appendForm (~/Projects/keystone/node_modules/transloadit/lib/TransloaditClient.js:234:24)
16:12:23 web.1  |   at TransloaditClient._remoteJson (~/Projects/keystone/node_modules/transloadit/lib/TransloaditClient.js:407:21)
16:12:23 web.1  |   at ~/Projects/keystone/node_modules/transloadit/lib/TransloaditClient.js:51:24
16:12:23 web.1  |   at ~/Projects/keystone/node_modules/transloadit/lib/TransloaditClient.js:281:20
16:12:23 web.1  |   at Request._callback (~/Projects/keystone/node_modules/transloadit/lib/TransloaditClient.js:404:16)
16:12:23 web.1  |   at Request.self.callback (~/Projects/keystone/node_modules/transloadit/node_modules/request/index.js:142:22)
16:12:23 web.1  |   at Request.emit (events.js:98:17)
16:12:23 web.1  |   at Request.<anonymous> (~/Projects/keystone/node_modules/transloadit/node_modules/request/index.js:856:14)
16:12:23 web.1  |   at Request.emit (events.js:117:20)
16:12:23 web.1  |   at IncomingMessage.<anonymous> (~/Projects/keystone/node_modules/transloadit/node_modules/request/index.js:808:12)
16:12:23 web.1  |   at IncomingMessage.emit (events.js:117:20)
16:12:23 web.1  |   at _stream_readable.js:943:16
16:12:23 web.1  |   at process._tickCallback (node.js:419:13)
16:12:23 web.1  | 17 Nov 16:12:23 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by pinkanasoft** [comment]
CreateHmac() function expects the algorithm to hash ['sha1'] and the salt (which is in bytes). In my case i have not passed byte salt instead string value. when bytes are passed this worked perfectly.
