### ISSUE TITLE
Are we missing an is undefined check?

### ISSUE THREAD

**Issue by kvz** [transloadit/node-sdk#48]
Just got:

```
/Users/kvz/code/content/node_modules/transloadit/lib/TransloaditClient.js:588
        var body = _ref5.body,
                        ^

TypeError: Cannot read property 'body' of undefined
    at Request._callback (/Users/kvz/code/content/node_modules/transloadit/lib/TransloaditClient.js:588:25)
    at self.callback (/Users/kvz/code/content/node_modules/transloadit/node_modules/request/request.js:187:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Timeout._onTimeout (/Users/kvz/code/content/node_modules/transloadit/node_modules/request/request.js:762:12)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

Only got the transpiled code: ![](https://dl.dropboxusercontent.com/s/o3q4j98av2xu41t/2017-09-06%20at%2017.01.png)

So that seems another issue, we don't ship working sourcemaps right now.

Patched around it via:

```
        if (err) {
          return cb(err);
        }

        if (!_ref5) {
          return cb(new Error('No data for request!'));
        }

        var body = _ref5.body,
            statusCode = _ref5.statusCode;
```

for now.

**Comment by tim-kos** [comment]
Alright, cheers. Will look into it.

**Comment by kvz** [comment]
After some thinking, I think we should not do es6 object deconstruction since this assumes the existence of object properties before checking for errors. Switching back to just an object and then checking for errors, and then checking for object properties likely resolves this already

**Comment by kvz** [comment]
@tim-kos handled

**Comment by tim-kos** [comment]
💪 👍
